name: moolwmsstore
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  shared_preferences:
  gap:
  # logger: ^2.0.2+1
  cached_network_image: ^3.3.1
  badges: ^3.1.2
  dropdown_button2: ^2.3.9
  # auto_route: ^8.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # responsive_sizer: ^3.3.0+1
  calendar_date_picker2: ^1.0.2
  image_picker: ^1.1.1
  get_it: ^7.6.7
  country_code_picker:
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2+1
  otp_text_field_v2: ^1.0.3
  percent_indicator: ^4.2.3
  dotted_border: ^2.1.0
  # qr_code_scanner: ^1.0.1
  intl:
  # image_picker_web:
  flutter_spinkit:
  smooth_page_indicator: ^1.1.0
  google_geocoding_api: ^1.5.2
  syncfusion_flutter_charts: ^25.1.39+1
  # getx_route_annotations:
  hive: ^2.2.3

  hive_flutter:
  path_provider:
  # qr_bar_code: ^1.2.0
  restart_app: ^1.2.1
  msh_checkbox: ^2.0.1
  # flutter_3d_controller: ^1.3.0
  # drag_select_grid_view: ^0.6.2
  zoom_widget: ^2.0.1
  # flutter_launcher_icons: ^0.13.1
  file_picker: ^8.0.3
  qr_bar_code_scanner_dialog: ^0.0.5
  throttling: ^2.0.1
  number_text_input_formatter: ^1.0.0+8
  # flutter_native_splash: ^2.4.0
  camera: ^0.11.0
  two_dimensional_scrollables: ^0.3.0
  interactive_viewer_2: ^0.0.8
  material_table_view: ^4.0.2
  widget_zoom: ^0.0.4
  fast_color_picker: ^0.1.1
  hexcolor: ^3.0.1
  iglu_color_picker_flutter: ^1.0.5
  easy_color_picker: ^1.0.0
  gif_view: ^0.4.3
  # board_datetime_picker: ^1.6.5
  # flutter_datetime_picker_plus: ^2.2.0
  omni_datetime_picker: ^1.1.0
  accordion: ^2.6.0
  # photo_view: ^0.15.0
  pinch_zoom: ^2.0.0
  pretty_qr_code: ^3.3.0
  infinite_scroll_pagination: ^4.0.0
  loading_animation_widget: ^1.2.1
  flutter_date_range_picker: ^0.1.1
  flutter_native_splash: ^2.4.0
  qr_flutter: ^4.1.0
  # whatsapp_share: ^2.0.2
  widgets_to_image: ^1.0.0
  # convert_widget_to_image: ^0.0.2
  share_plus: ^9.0.0
  qr_scanner_overlay: ^0.0.2
  flutter_svg: ^2.0.10+1

  # lazy_load_scrollview: ^1.3.0

  # flutter_spinkit: ^5.2.0
  # flutter_localization: ^0.2.0
  # accordion: ^2.6.0
  # lottie: ^3.0.0
  # retrofit: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # auto_route_generator: ^8.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter_launcher_icons:
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/appLogo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/Layer_5.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/languages/
    - assets/images/
    # - assets/3d/
    - assets/gifs/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/font/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/font/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/font/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/font/SF-Pro-Display-Black.otf
          weight: 900
