name: moolwmsstore
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  platform_detector: ^0.2.0
  shared_preferences:
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  gap:
  fl_country_code_picker: ^0.1.9+1
  flutter_localization: ^0.2.0
  logger: ^2.0.2+1

  flutter_otp_text_field: ^1.1.1
  accordion: ^2.6.0
  flutter_carousel_widget: ^2.2.0
  hexcolor: ^3.0.1
  syncfusion_flutter_charts: ^24.1.43+1
  cached_network_image:
  badges: ^3.1.2
  dropdown_button2:
  image_network: ^2.5.4+1
  auto_route: ^7.8.4
  lottie: ^3.0.0
  retrofit: ^4.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  animated_toggle_switch: ^0.8.0
  calendar_date_picker2: ^0.5.3
  image_picker: ^1.0.7
  flutter_spinkit: ^5.2.0
  

 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/slider_images/
    - assets/images/drawer_images/
    - assets/lang/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
